import { ArrowRight, ChevronDown, FileCheck2, ShieldCheck } from 'lucide-react';
import type { AnalysisResult, CellValue, RecordingSummary } from '../../types/multisystem';
import type { DoorAnalysis } from '../../lib/railwitnessDoorClient';
const displayNumber = (value: CellValue | undefined) => value === undefined || value === null || value === '' ? 'Not recorded' : typeof value !== 'number' ? value : value !== 0 && (Math.abs(value) < .001 || Math.abs(value) >= 1e6) ? value.toExponential(5) : Number(value.toPrecision(7)).toLocaleString('en-SG', { maximumFractionDigits: 7 });

export default function ResultSummary({ result, recording, onCycle, doorAnalysis, selectedCycle, concealReplay = false }: { result: AnalysisResult | null; recording?: RecordingSummary; onCycle: (index: number) => void; doorAnalysis?: DoorAnalysis; selectedCycle?: number | null; concealReplay?: boolean }) {
  return <section className={`ms-result ${result ? 'is-computed' : ''}`} aria-label="Prediction result">
    <div className="ms-result-label"><span className={`ms-kind ${result ? 'predicted' : 'metadata'}`}>{result ? 'Predicted' : 'Not analysed'}</span><span>{result?.source.mode === 'demo' ? 'SYNTHETIC DEMONSTRATION' : 'SCOPED MODEL OUTPUT'}</span></div>
    {!result ? <div className="ms-result-empty"><FileCheck2 size={23}/><div><h2>{recording ? 'Recording ready for analysis' : 'Choose a recording to begin'}</h2><p>{recording ? 'Run analysis to produce a result. Missing predictions are never shown as Normal.' : 'Upload a supported file or explore a clearly labelled synthetic demonstration.'}</p></div></div> : <>
      <div className="ms-result-main"><div>
        <h2>{result.subsystem === 'rail' ? result.prediction === 'Normal' ? 'Predicted: Normal' : `Predicted: ${result.prediction} corrugation` : result.subsystem === 'acv' ? `Highest-ranked suspected carriage: ${result.rankedCars[0]}` : result.subsystem === 'shm' ? 'Predicted cumulative fatigue damage' : `${result.segments.length} door cycles classified`}</h2>
        {result.subsystem === 'shm' && <output className="ms-damage" title={String(result.predictedDamage)}>{displayNumber(result.predictedDamage)}</output>}
        <p>{result.subsystem === 'rail' ? 'One class for this recording. Rail highlighting denotes the reference side; it does not locate a defect along a physical track.' : result.subsystem === 'acv' ? 'One ordered ranking for the full case. Rank is not a probability, leak rate, or a verified healthy status.' : result.subsystem === 'shm' ? 'Scope: this recording / stress segment. No health percentage, remaining-life estimate or train-wide sum.' : 'One classification per completed recorded cycle, with its original start and end times.'}</p>
      </div><span className="ms-result-scope">{result.scope === 'car-case' ? 'FULL CASE' : result.scope.toUpperCase()}</span></div>
      {result.subsystem === 'acv' && <ol className="ms-ranking" aria-label="Complete car ranking">{result.rankedCars.map((car, rank) => <li key={car}><span>{rank + 1}</span><strong>{car}</strong>{rank === 0 && <span>Highest rank</span>}</li>)}</ol>}
      {doorAnalysis && !concealReplay && <div className="ms-door-summary" aria-label="Door analysis summary"><span><strong>{doorAnalysis.summary.normal}</strong> Normal</span><span><strong>{doorAnalysis.summary.abnormal_resistance}</strong> Abnormal resistance</span><span><strong>{doorAnalysis.summary.rows.toLocaleString()}</strong> source rows</span><span>Frozen Python model · {doorAnalysis.model_id}</span></div>}
      {result.subsystem === 'door' && !concealReplay && <div className="ms-segments"><table><caption>Predicted segments · {result.source.fileName}</caption><thead><tr><th>Start time</th><th>End time</th><th>Prediction</th><th>Inspect</th></tr></thead><tbody>{result.segments.map((segment, index) => <tr key={`${segment.start_time}-${index}`}><td>{segment.start_time}</td><td>{segment.end_time}</td><td><span className={segment.prediction === 'Normal' ? 'ms-neutral-result' : 'ms-amber'}>{segment.prediction}</span></td><td><button className="ms-text-button" aria-pressed={selectedCycle === index} onClick={() => onCycle(index)}>Cycle {index + 1}<ArrowRight size={12}/></button></td></tr>)}</tbody></table>{!result.segments.length && <p>No complete cycles were detected in this stream.</p>}</div>}
      {result.subsystem === 'door' && concealReplay && <p className="ms-replay-pending" role="status">Recorded movement replay · classification is revealed when the cycle finishes.</p>}
      {result.subsystem === 'shm' && <dl className="ms-mapping-details"><div><dt>Measurement-point identity</dt><dd>{result.mapping.status === 'mapped' && result.mapping.anchor.kind === 'measurementPoint' ? result.mapping.anchor.pointId : 'Not supplied'}</dd></div><div><dt>Physical location</dt><dd>{result.mapping.status === 'mapped' ? result.mapping.provenance : 'Not supplied · no component is highlighted'}</dd></div></dl>}
      <details className="ms-model"><summary><ShieldCheck size={12}/>{result.model.name}<span>{result.model.version}</span><ChevronDown size={12}/></summary><div><p>{result.model.description}</p><p><strong>Training</strong> {result.model.training}</p><p><strong>Validation</strong> {result.model.validation}</p>{result.notes.map(note => <p key={note}>{note}</p>)}<p><strong>Source</strong> {result.source.datasetId} / {result.source.fileName} · {result.analysedAt}</p></div></details>
    </>}
  </section>;
}

