import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const baseUrl = process.env.RAILWITNESS_URL || 'http://127.0.0.1:5173';
const captureDir = process.env.RAILWITNESS_CAPTURE_DIR || '/private/tmp/railwitness-v2';
await mkdir(captureDir, { recursive: true });
const browser = await chromium.launch({channel:'chrome', headless:true, args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1,reducedMotion:'reduce'});
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if(message.type()==='error') errors.push(message.text()); });
await page.goto(baseUrl);
await page.locator('.train-scene[data-ready="true"]').waitFor({ timeout: 30000 });
await page.screenshot({path:`${captureDir}/overview.png`,fullPage:true});
await page.getByRole('button', {name:'Test this prediction'}).click();
await page.getByText('The signature repeated.', {exact:true}).waitFor();
console.log('Reveal verified:', baseUrl);
await page.getByRole('button', {name:'Door analysis',exact:true}).click();
await page.screenshot({path:`${captureDir}/analysis.png`,fullPage:true});
await page.getByRole('button', {name:'Verification',exact:true}).click();
await page.screenshot({path:`${captureDir}/verification.png`,fullPage:true});
console.log('Title:',await page.title());
console.log('Canvas:', await page.locator('canvas').count());
console.log('Document dimensions:', await page.evaluate(()=>({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,viewport:innerWidth})));
await browser.close();
if (errors.length) throw new Error(errors.join('\n'));
